version: '3'
services:
    purlovia:
        image: coldino/purlovia:live

        container_name: purlovia_runner
        hostname: purlovia_runner

        volumes:
          - ./livedata:/app/livedata:delegated
          - ./logs:/app/logs:delegated
          - ./output:/app/output
          - ./config:/app/config:ro

        command:
            python -m automate --live
